import { admin, employee } from "./data.js";

export const negativeEmployeeCases = [
  {
    name: "missing first name",
    firstName: "",
    lastName: employee.AddEmp.lastName,
    employeeId: Math.floor(Date.now() / 1000),
    employeePhoto: employee.AddEmp.employeePhoto,
    expectFieldError: true,
    expectGlobalError: false,
  },
  {
    name: "missing last name",
    firstName: employee.AddEmp.firstName,
    lastName: "",
    employeeId: Math.floor(Date.now() / 1000),
    employeePhoto: employee.AddEmp.employeePhoto,
    expectFieldError: true,
    expectGlobalError: false,
  },
  {
    name: "duplicate employee id",
    firstName: employee.AddEmp.firstName,
    lastName: employee.AddEmp.lastName,
    employeeId: 1235,
    employeePhoto: employee.AddEmp.employeePhoto,
    expectFieldError: false,
    expectGlobalError: true,
  },
];

export const negativeUserCases = [
  {
    name: "missing user role",
    userRole: "",
    employeeName: "Ranga Akunuri",
    status: "Enabled",
    username: admin.addUserInfo.username,
    password: admin.addUserInfo.password,
    confirmPassword: admin.addUserInfo.confirmPassword,
    expectedError: "Required",
  },
  {
    name: "missing employee name",
    userRole: "ESS",
    employeeName: "",
    status: "Enabled",
    username: admin.addUserInfo.username,
    password: admin.addUserInfo.password,
    confirmPassword: admin.addUserInfo.confirmPassword,
    expectedError: "Required",
  },
  {
    name: "missing status",
    userRole: "ESS",
    employeeName: "Ranga Akunuri",
    status: "",
    username: admin.addUserInfo.username,
    password: admin.addUserInfo.password,
    confirmPassword: admin.addUserInfo.confirmPassword,
    expectedError: "Required",
  },
  {
    name: "missing username",
    userRole: "ESS",
    employeeName: "Ranga Akunuri",
    status: "Enabled",
    username: "",
    password: admin.addUserInfo.password,
    confirmPassword: admin.addUserInfo.confirmPassword,
    expectedError: "Required",
  },
  // {
  //   name: "missing password",
  //   userRole: "ESS",
  //   employeeName: "Ranga Akunuri",
  //   status: "Enabled",
  //   username: admin.addUserInfo.username,
  //   password: "",
  //   confirmPassword: "",
  //   expectedError: "Should have at least 7 characters",
  // },
  {
    name: "passwords do not match",
    userRole: "ESS",
    employeeName: "Ranga Akunuri",
    status: "Enabled",
    username: admin.addUserInfo.username,
    password: "Password1!",
    confirmPassword: "Mismatch!",
    expectedError: "Passwords do not match",
  },
];
